/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Building(props) {
  const { nodes, materials } = useGLTF("/Large Building.glb");
  return (
    <group {...props} dispose={null}>
      <group>
        <group name="large_buildingE">
          <mesh
            name="large_buildingE_1"
            castShadow
            receiveShadow
            geometry={nodes.large_buildingE_1.geometry}
            material={materials._defaultMat}
          />
          <mesh
            name="large_buildingE_1_1"
            castShadow
            receiveShadow
            geometry={nodes.large_buildingE_1_1.geometry}
            material={materials.border}
          />
          <mesh
            name="large_buildingE_1_2"
            castShadow
            receiveShadow
            geometry={nodes.large_buildingE_1_2.geometry}
            material={materials.window}
          />
          <mesh
            name="large_buildingE_1_3"
            castShadow
            receiveShadow
            geometry={nodes.large_buildingE_1_3.geometry}
            material={materials.door}
          />
          <mesh
            name="large_buildingE_1_4"
            castShadow
            receiveShadow
            geometry={nodes.large_buildingE_1_4.geometry}
            material={materials.roof}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/Large Building.glb");
